uint32 ACTION_ARM_ROBOT = 1
uint32 ACTION_MISSION = 2
uint32 ACTION_CONFIGURE = 3

uint32 INVOKE_STOP = 11
uint32 INVOKE_EMERGENCY = 12 

uint32 TYPE_START = 254
uint32 TYPE_STOP = 255

string node_name        # who asks
uint32 action_id        # what action
uint32 request_type     # Start or Stop?
string controller_names # which ros2_controller should be activated
---
# Response
bool success          # was the request granted?
string message        # optional reason